version: "3.8"
#
# Services definitions
#
services:
    app:
        container_name: patients_api
        image: kooldev/php:8.1-nginx
        ports:
            - "${KOOL_APP_PORT:-8565}:80"
        environment:
            ASUSER: "${KOOL_ASUSER:-0}"
            UID: "${UID:-0}"
        volumes:
            - .:/app:delegated
        networks:
            - light_it_network
    database:
        container_name: patients_db
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "${DB_PORT-3878}:3306"
        volumes:
            - patients_volume:/var/lib/mysql
        networks:
            - light_it_network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]
#
# Networks definitions
#
networks:
    light_it_network:
volumes:
    patients_volume:
